### ISSUE TITLE
timespan different for same dates issues

### ISSUE THREAD

**Issue by mafragias** [ArtResearch/pharos-mappings#100]
Timespan generator uses the id of the subject/object for the creation of the uris. Because of this in the structured search we have multiple labels for the same date (eg 1540). We need to resolve this.

**Comment by mafragias** [comment]
Possible Solution : instead of timespan URI, have only date.
Right Now is : 
<https://pharos.artresearch.net/resource/zeri/work/455> fr:Work_to_Date <https://pharos.artresearch.net/resource/zeri/work/455/production/timespan>.
<https://pharos.artresearch.net/resource/zeri/work/455/production/timespan> rdfs:label "1010";
rdfs:label "1000".
<https://pharos.artresearch.net/resource/zeri/work/455> fr:Work_from_Date <https://pharos.artresearch.net/resource/zeri/work/455/production/timespan>.
<https://pharos.artresearch.net/resource/zeri/work/455/production/timespan> rdfs:label "1010";
rdfs:label "1000".

Example Solution : 
<https://pharos.artresearch.net/resource/zeri/work/455> fr:Work_from_Date "1000".
<https://pharos.artresearch.net/resource/zeri/work/455> fr:Work_to_Date "1010".

**Comment by MinadakisNikos** [comment]
lets do it

**Comment by mafragias** [comment]
Example Work Output : 

```
<fr:Place_of_Work>
              <fc:work rdf:about="https://pharos.artresearch.net/resource/marburg/work/20770706">
                <fr:Work_from_Date>um 1800</fr:Work_from_Date>
              </fc:work>
            </fr:Place_of_Work>
            <fr:Place_of_Work>
              <fc:work rdf:about="https://pharos.artresearch.net/resource/marburg/work/20770628">
                <fr:Work_from_Date>1701/1750</fr:Work_from_Date>
              </fc:work>
            </fr:Place_of_Work>
            <fr:Place_of_Work>
              <fc:work rdf:about="https://pharos.artresearch.net/resource/marburg/work/20770733">
                <fr:Work_from_Date>1775</fr:Work_from_Date>
              </fc:work>
            </fr:Place_of_Work>
```

Example Photo Output :
 
```
<fr:Photographer_photographed_Photo>
      <fc:photo rdf:about="https://pharos.artresearch.net/resource/marburg/photo/fm95991">
        <fr:Photo_from_Date>1900/1925</fr:Photo_from_Date>
      </fc:photo>
    </fr:Photographer_photographed_Photo>
    <fr:Photographer_photographed_Photo>
      <fc:photo rdf:about="https://pharos.artresearch.net/resource/marburg/photo/fm94922a">
        <fr:Photo_from_Date>1900/1925</fr:Photo_from_Date>
      </fc:photo>
    </fr:Photographer_photographed_Photo>
    <fr:Photographer_photographed_Photo>
      <fc:photo rdf:about="https://pharos.artresearch.net/resource/marburg/photo/fm95177">
        <fr:Photo_from_Date>1900/1925</fr:Photo_from_Date>
      </fc:photo>
    </fr:Photographer_photographed_Photo>
```
