### ISSUE TITLE
Add Photomechanical Print Addition 

### ISSUE THREAD

**Issue by mafragias** [ArtResearch/pharos-mappings#105]
Add photomechanical print type for photos

**Comment by spykoulouris** [comment]
Could you give me some context here? What is it that I should do?
Photomechanical prints and photographic prints are two different things.

**Comment by mafragias** [comment]
We need instructions on how to identify a photomechanical print in your data, as you suggested in a previous call. We will also need the AAT URI.

**Comment by spykoulouris** [comment]
Here is the AAT URI: http://vocab.getty.edu/aat/300041424

**Comment by MinadakisNikos** [comment]
@mafragias is this added now?

**Comment by mafragias** [comment]
@MinadakisNikos  It is not fixed, because we didn't have instructions on where to add the URI.

**Comment by MinadakisNikos** [comment]
@spykoulouris how to identify a photomechanical print in your data? it is a type?

**Comment by spykoulouris** [comment]
yes it is a type of the photograph (not the artwork)

**Comment by mafragias** [comment]
Added in mappings, it will be available in the next data import
