### ISSUE TITLE
Middle East Built Works

### ISSUE THREAD

**Issue by spykoulouris** [ArtResearch/pharos-mappings#127]
Not sure what has happened here. The same image is linked with different built works
https://artresearch.net/resource/?uri=Default%3ADisplayCollectionBuiltworksMiddleEast&semanticSearch=N4IgZiBcDaC6A0IBOBTAzgVwDYBcrAF9EATAQx1LRRzSjkVKwEsBzAOwFsU29JQAVKCAAi5UgDoAsqQCeAIxQhEANXwEiIFklIAHABYBlAMYB7HSgMpSSI3vwhBkEWKmyFSkKr7qCQA

For instance the Kasbah of Sousse is linked with completely wrong images:
https://artresearch.net/resource/?uri=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fitatti%2Fwork%2F8001623126

this is the original record in Hollis images (the original record link in our UI does not work):
http://id.lib.harvard.edu/images/8001623126/catalog

**Comment by MinadakisNikos** [comment]
spyros this issue comes out because of the _1 _2 implementations. we took a look at the records and saw that for buildworks there is no _ even if we are not having a digital image. So we will add a conditions that if we have a builtwork the the accession number of the image is without _

**Comment by spykoulouris** [comment]
Ok Nikos. We have been correcting this error in our data. I will check with my colleague to see if all the Built Work records have been fixed. You don't need to do anything. In the next refresh of the records the problem will be hopefully fixed.

**Comment by spykoulouris** [comment]
Can you check again this? It seems the error was fixed but now many of the Middle East records have no images. 
sometimes the same image appears in many records
