### ISSUE TITLE
Collections Highlights (Built Works)

### ISSUE THREAD

**Issue by spykoulouris** [ArtResearch/pharos-mappings#128]
The Built Works query in the home page (collections highlights) brings you to the repositories list not the built works list.

Once this is done can we create a map showing all built works (similar to the one of the repositories)?

**Comment by mafragias** [comment]
Built work type to be added in the data for all.

**Comment by mafragias** [comment]
added type http://vocab.getty.edu/aat/300265418 (built works) to all MIDAS builtwork mappings and in SharedShelf for the case where the original type is http://forum.jstor.org/oai/AAT/300265418.

We don't have a way to distinguish the builtworks, if there are any in the other providers.
