### ISSUE TITLE
Photographers missing

### ISSUE THREAD

**Issue by spykoulouris** [ArtResearch/pharos-mappings#129]
It seems there are some photographers missing from the dataset (i.e. Foto Reali, Centrica, M.N. Conger)

**Comment by mafragias** [comment]
Photographer Foto Reali exist here:
https://artresearch.net/resource/?uri=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fitatti%2Factor%2F9000418537.

The reason on why they are not show is because they have not been matched with NYPL photographer yet.

**Comment by spykoulouris** [comment]
I see, thanks!

**Comment by MinadakisNikos** [comment]
close this only when the reconciliation is fixed
