### ISSUE TITLE
use of hashes in URI generator policies

### ISSUE THREAD

**Issue by lklic** [ArtResearch/pharos-mappings#132]
on this issue:
https://github.com/ArtResearch/pharos-mappings/issues/85#issuecomment-776788910

I noticed that these vocabulary terms still use a hash for the URI. This will need to be replaced with the respective ID from the vocab. We should avoid hashes where possible and use the original ID's.

**Comment by mafragias** [comment]
I can remove the hash, when there is an ID.

**Comment by mafragias** [comment]
Example  for itatti where there is ID : https://pharos.artresearch.net/resource/itatti/vocabulary/technique/300128695

**Comment by MinadakisNikos** [comment]
perfect close it

**Comment by mafragias** [comment]
Issue Validated
