### ISSUE TITLE
duplicate nodes across named graphs

### ISSUE THREAD

**Issue by lklic** [ArtResearch/pharos-mappings#133]
as discussed, we cannot have every term, type, person, etc, node be duplicated across named graphs.

https://artresearch.net/resource/?showStatements=true&uri=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Ffrick%2Ftype%2FR1A3V0CK

It will take several iterations of data transformation to clean this up so please give it some priority.

**Comment by mafragias** [comment]
This is a duplicate issue of this https://github.com/ArtResearch/pharos-mappings/issues/102

**Comment by MinadakisNikos** [comment]
great close it

**Comment by mafragias** [comment]
Issue Validated
