### ISSUE TITLE
escaped quote characters in VIT data

### ISSUE THREAD

**Issue by lklic** [ArtResearch/pharos-mappings#139]
on the attribution note for I Tatti records, quotes are escaped and not visualized properly in the field:
https://artresearch.net/resource/?uri=https://pharos.artresearch.net/resource/pharos/artwork/024282516

**Comment by mafragias** [comment]
I have fixed the issue in presentation of the field. However, this is how the data are downloaded, to avoid any parsing issues.
It may presented in http://oai.forum.jstor.org/oai/ssw/8000655442 as " but downloaded as &quot; because the quotes are inside quotes.

**Comment by lklic** [comment]
Thanks for fixing.

I guess we should do the same for all of the fields...
