### ISSUE TITLE
Shared Shelf and Foto Index

### ISSUE THREAD

**Issue by spykoulouris** [ArtResearch/pharos-mappings#143]
I wonder whether we can merge all I Tatti records together (the ones coming from Shared Shelf with those from Foto Index), so they show up together in the home page. Has there already been a discussion about that? I don't know if there will be any issues related to that.

Users will not understand what is the difference of the two categories if we keep them as they are. Any suggestions? @lklic @MinadakisNikos

**Comment by MinadakisNikos** [comment]
fine for me if Luka agrees obviously

**Comment by MinadakisNikos** [comment]
should we proceed with this?

**Comment by MinadakisNikos** [comment]
@spykoulouris @lklic do we need to do this?

**Comment by spykoulouris** [comment]
@lklic can we (also) talk about this?
