### ISSUE TITLE
FotoIndex Missing Institutions

### ISSUE THREAD

**Issue by mafragias** [ArtResearch/pharos-mappings#144]
So I noticed that multiple works have Institution (P29) with id N0000000, but in the list of institutions provided it doesn't exist. I think it is probably a mistake, because the id has 7 digits where all the other institution/work/artist ids have 8 digits.

```
   <Work>
      <Artwork_ID>W00012545</Artwork_ID>
      <E21_ID>A00000522</E21_ID>
      <P29>N0000000</P29>
   </Work>
   <Work>
      <Artwork_ID>W00026312</Artwork_ID>
      <E21_ID>A00000226</E21_ID>
      <P29>N0000000</P29>
   </Work>
   <Work>
      <Artwork_ID>W00012523</Artwork_ID>
      <E21_ID>A00000522</E21_ID>
      <P29>N0000000</P29>
   </Work>
```

**Comment by lklic** [comment]
The corrected data has been uploaded to our shared drive:
FINAL_EXPORT_16-03-2021

Here are the updated IDs

Type | Format | # of chars | 
-- | -- | -- |
Work ID | W05135446 | 9
Institution ID | N00025252 |9| 
Photo ID | P00025252 |9|   
Artist ID | A00000242 |9| 
Collection ID | C00002544 |9 |

**Comment by mafragias** [comment]
Closing this issue with the note that all the photo ids have 10 chars, otherwise the ids seem to be correct.

Type | Format | # of chars
-- | -- | --
Photo ID | P00025252 | 10
-- | -- | --
