### ISSUE TITLE
Zeri image URI's not generated properly

### ISSUE THREAD

**Issue by lklic** [ArtResearch/pharos-mappings#145]
they are being generated as such:
<https://iiif.artresearch.net/iiif/2/zeri!134000%21133988_g.jpg/full/full/0/default.jpg>

The second `!` is being escaped as `%21` but it should not.

Also many of these images are not present, I have found a list through the pastec logs...

**Comment by mafragias** [comment]
The engine has been refactored and Image URI will not have escape character : 

```
https://iiif.artresearch.net/iiif/2/zeri!9600!9436_g.jpg/full/full/0/default.jpg
```

Also after the next upload the rest of the images will be present.
