### ISSUE TITLE
I Tatti records repository: Biblioteca Berenson

### ISSUE THREAD

**Issue by spykoulouris** [ArtResearch/pharos-mappings#146]
I see there have been imported Shared Shelf work records with repository "Biblioteca Berenson, I Tatti - The Harvard University Center for Italian Renaissance Studies". ([example here](https://artresearch.net/resource/?uri=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fitatti%2Fwork%2F8000792834))
All these records should be excluded from the dataset. 

From I Tatti's shared shelf records we should only include the ones from the following two repositories (in either work or photograph records):

1. Berenson Art Collection, I Tatti - The Harvard University Center for Italian Renaissance Studies ([example](https://artresearch.net/resource/?uri=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fitatti%2Fwork%2F8000791797))
2. Biblioteca Berenson, Fototeca, I Tatti - The Harvard University Center for Italian Renaissance Studies ([example](https://artresearch.net/resource/?uri=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fitatti%2Fwork%2F8001623127))

**Comment by spykoulouris** [comment]
What is the difference between the relations "kept by" and "has provider" when referring to photographs owned by an institution? there are very few results when searching for photos owned by I Tatti (and those are photos that should be excluded as indicated in this ticket).
![repository](https://user-images.githubusercontent.com/73180833/113864015-ad243d80-97aa-11eb-924e-1e8fed75a5c2.PNG)

**Comment by spykoulouris** [comment]
I re-open this. There are still images that shouldn't be in the platform
example: https://artresearch.net/resource/?keyword=tripoli%2A&uri=rsp%3AFilterSearch&semanticSearch=N4IgZiBcDaoE4FMrwIZRAHgBYBccAcBnSAehPyxTgHtCA6KnRQhKgYyzoDsEcTnqAVzhsEJMGxIBLLoRxScg%2BdS4A%2BEABoQidNjxFS5SjXqNmrEZx58Bw0eLgkA6tTgBrAPqVCH-DQBuUgAmCHAeAJKy8orKapogQVDQ0CAASgiEQiJIGqBScFLIIAAq6OEF8QBqRTihALbFAJ74SJAgAHIodQhB7dQh8f4oADaCrSC4BMRkFFS0DHBMGRYc3Lz8GVn2Cih4UiSZdmLhxbvyIAC%2BF1rDKABGCMNlAASne-EhhGwF%2BLEvb%2BctIp8MNWqAhqMwSUyhUtNVIKBanAGs1xp1ur1%2BjkQBCxuhJgYZsZ5mZluwrOtbNlpDgzvtDtSTnTLtcQGwhFwcEVSm0ADIKUIjKo1epNFroflIoVaXHjACsAAYPrtdqjuTDCnCRcixWiuj0%2BgMZSM8W0CYYAO5WugWgDMdFcAHMSAAmBUKgCMJAAGgBZXkAZQ4CDqKAAxDJao7QiybiguI7BCho%2BhYyBbg8ngjoXyBXBpSB4YjRWrc1KnsbIf9mVogiqcKXQDyQOVNYXtSjxW10QasYMTeNzWQrRabfana73V6-YHg6Gw3ICgm07cE0mU20WVcALrbndaZiCYZchGsuu0lg4QhJbdaEZSR1cbqc9VtAAiKrovpQjQewtPrKOvmFBBtQLQBisWCviAH60l%2BP5-lqAEXEAA

**Comment by MinadakisNikos** [comment]
spyro I closed it because it has been fixed in dev.artresearch. Lets go through together to our call and re-close it :)

**Comment by mafragias** [comment]
The sets that exist in the OAI are :
set number | set name
809 | Berenson Art Collection
810 | Biblioteca Berenson
811 | Biblioteca Berenson, Fototeca

In my understanding the set 810 should be deleted. Can @spykoulouris confirm that this is correct?

**Comment by spykoulouris** [comment]
Exactly. Thank you.

**Comment by spykoulouris** [comment]
Do you have any updates?

There are still records that should be deleted.

example:
https://artresearch.net/resource/?uri=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fpharos%2Fartwork%2F243dd4e246b1a4c95488af3c51f641cbfaa147dd

**Comment by mafragias** [comment]
The were some materializations that were not properly deleted . However, if you check the example you provided,  doesn't exist anymore.
