### ISSUE TITLE
missing image titles

### ISSUE THREAD

**Issue by lklic** [ArtResearch/pharos-mappings#147]
we have titles for some photographs:
https://images.hollis.harvard.edu/primo-explore/viewcomponent/L/HVD_VIAolvwork740842?vid=HVD_IMAGES&imageId=urn-3:VIT.BB:22490178&adaptor=

you can see this under image information (Detail: infrared reflectography)

This is missing in the photo record, and should also be the title of the photograph rather than the ID.
https://artresearch.net/resource/?uri=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fitatti%2Fphoto%2F500485

**Comment by MinadakisNikos** [comment]
any news?
