### ISSUE TITLE
Harvard Fine Arts Library records

### ISSUE THREAD

**Issue by spykoulouris** [ArtResearch/pharos-mappings#149]
Can you check how many photograph records have been exported with repository "Harvard Fine Arts Library"? These should not be included in Pharos, although in many cases I Tatti and the Fine Arts Library have linked their photograph records with the same artwork record.

example: https://artresearch.net/resource/?uri=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fitatti%2Fphoto%2F1998.121

**Comment by mafragias** [comment]
closed as duplicate of https://github.com/ArtResearch/pharos-mappings/issues/157
