### ISSUE TITLE
Mapping between TGN and Geonames, materialization of Geonames hierarchies

### ISSUE THREAD

**Issue by lklic** [ArtResearch/pharos-mappings#150]
Since we are using Geonames as our authority for place names, I think we should have a mapping between geonames and TGN, probably using wikidata as a bridge.

This way we can search for hierarchies of places, as they have in the BM RS instance, to be able to select a region in a specific part of the world and visualize all events (actor birth, death, active in, etc) that take place within that region.

I think we should materialize all relevant geonames hierarchical data for a specific location to use as our lookup.

**Comment by MinadakisNikos** [comment]
we are on it

**Comment by MinadakisNikos** [comment]
@mafragias this is done right?

**Comment by mafragias** [comment]
This has been implemented. And the materializations have been completed for fr:Artist_from_Place, fr:Place_of_Artist, fr:Work_from_Place, fr:Place_of_Work, fr:Institution_from_Place. Let me know, if there's anything else.
