### ISSUE TITLE
Former Locations missing

### ISSUE THREAD

**Issue by spykoulouris** [ArtResearch/pharos-mappings#151]
In many Zeri artwork records the Former Locations are missing.
In this record there is only the current location:
https://artresearch.net/resource/?uri=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fpharos%2Fartwork%2F01602567

the original record includes two former locations: http://catalogo.fondazionezeri.unibo.it/scheda/opera/4989/

**Comment by MinadakisNikos** [comment]
ToCheck on the original data @mafragias

**Comment by mafragias** [comment]
fixed in mappings, it will be visible with the next data import.

**Comment by MinadakisNikos** [comment]
ficed https://dev.artresearch.net/resource/?uri=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fpharos%2Fartwork%2F01602567

**Comment by MinadakisNikos** [comment]
@spykoulouris can you confirm so we will close it?

**Comment by spykoulouris** [comment]
Shouldn't we be able to see also the name of the cities (in this case London, Londra) and dates?

**Comment by spykoulouris** [comment]
![zeri](https://user-images.githubusercontent.com/73180833/117004208-1b92e780-ace6-11eb-8c24-b2da6061d90c.PNG)

**Comment by MinadakisNikos** [comment]
@mafragias what about this
