### ISSUE TITLE
Attribution values missing

### ISSUE THREAD

**Issue by spykoulouris** [ArtResearch/pharos-mappings#152]
Attribution values are missing from the Zeri artworks records (i.e. school of, circle of, etc.)

In this example the "bottega" (workshop) value is missing from the Attributions field.
https://artresearch.net/resource/?uri=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fpharos%2Fartwork%2F047835535

original record: http://catalogo.fondazionezeri.unibo.it/entry/work/29041/

The attribution value should be visualized together with the name of the artist.

**Comment by MinadakisNikos** [comment]
to check on the original data 29041

**Comment by MinadakisNikos** [comment]
https://dev.artresearch.net/resource/?uri=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fpharos%2Fartwork%2F047865139 fixed
