### ISSUE TITLE
Subject field (Zeri artwork record)

### ISSUE THREAD

**Issue by spykoulouris** [ArtResearch/pharos-mappings#154]
The subjects of the Zeri artworks records are not displayed correctly. 
https://artresearch.net/resource/?uri=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fpharos%2Fartwork%2F047865139

"visual_item" does not exist as a subject heading:

![Inkedsubject_zeri_LI](https://user-images.githubusercontent.com/73180833/112858944-aadb2880-90b2-11eb-8348-b9e97bea8aa3.jpg)

**Comment by MinadakisNikos** [comment]
@mafragias its solved right?

**Comment by MinadakisNikos** [comment]
fixed
