### ISSUE TITLE
Harvard Fine Arts Library photograph records

### ISSUE THREAD

**Issue by spykoulouris** [ArtResearch/pharos-mappings#157]
The photograph records of Harvard's Fine Arts Library have been exported together with I Tatti's ones. Those should be deleted. That is in these cases we need to keep the artwork records and only I Tatti's photograph records.
![Capture](https://user-images.githubusercontent.com/73180833/112843364-ca6a5500-90a2-11eb-9b1f-de68afde4915.PNG)

example: https://artresearch.net/resource/?uri=https://pharos.artresearch.net/resource/pharos/artwork/024282516

**Comment by mafragias** [comment]
for the two repositories below, the photos will not be mapped :
id=9000369831 |Harvard Fine Arts Library, Digital Images & Slides Collection
id=9000369124 |Harvard Fine Arts Library, Special Collections

If you approve this, the change will be visible after the next data import.

**Comment by spykoulouris** [comment]
Sounds great, thanks!
