### ISSUE TITLE
Issue with Hertziana IIIF

### ISSUE THREAD

**Issue by MinadakisNikos** [ArtResearch/pharos-mappings#160]
Hertziana IIIF images could be accessed this way  https://foto.biblhertz.it/exist/foto/bh000974/manifest.json for this photo:

http://fotothek.biblhertz.it/bh/320px/bh000974.jpg for example.

Now it returns the following error 
Hertziana in den folgenden Verbünden.
The photo catalogue (foto.biblhertz.it) is temporary unavailable. Please try again later or use our photos at

Need to see with them why

**Comment by mafragias** [comment]
full hertziana image : https://img.biblhertz.it/Scaler/IIIF/fototeca%212048px%2100%21bh000974/full/full/0/default.jpg
