### ISSUE TITLE
Photographers IDs when PIC is not there

### ISSUE THREAD

**Issue by MinadakisNikos** [ArtResearch/pharos-mappings#162]
PIC ids do not cover the whole Photographes set that we have. Need to decide how to handle this.

**Comment by spykoulouris** [comment]
what about using Wikidata? And if the name cannot be found in Wikidata, we can create it

**Comment by lklic** [comment]
I think if there is no PIC ID for a photographer we can try to use wikidata, and if not then mint a Pharos URI

**Comment by spykoulouris** [comment]
@MinadakisNikos  if you send me a list of the photographers with no PIC ID, I can create wikidata items for them and send you back the updated list with the wikidata IDs

**Comment by MinadakisNikos** [comment]
@mafragias have we sent this list to spyros? if not please send it asap

**Comment by mafragias** [comment]
@spykoulouris  Here is a list of the photographers on the platform:  https://docs.google.com/spreadsheets/d/1bHDzhiuCgfvEAO9iiEX5Vnbj7Q3kBOet51xSXuZchc8
These list have some suggested matches with PIC data, these matches have not been verified.

**Comment by MinadakisNikos** [comment]
@spykoulouris any news on this?

**Comment by spykoulouris** [comment]
Not sure what decided here. We need discuss this and issue #117 further. @lklic can we have a call about this?

**Comment by MinadakisNikos** [comment]
we decided to use wikidata and implemented it
