### ISSUE TITLE
Marburg extra fields for photos

### ISSUE THREAD

**Issue by MinadakisNikos** [ArtResearch/pharos-mappings#163]
We need to include more fields from marburg for the photo ids as described below:

1. We uploaded our images (~1,6 m) to Amazon S3 Bucket, and this is how
we did it:

(1) First you have to check if <a8541>gesperrt</a8541> exists in
<a8450>, in this case we do not have the right to share the image.
(2) If <a8541> does not exist, then <a8540> can be selected.
(3) If <a8540> does not exist, the first <a8555> (last scan of the
image) can be selected.
(4) If <a8555> does not exist, this means that the image has not yet
been digitized.

2. We have extended the google document. We corrected the translations
and tried to find a general solution (see column Semantics). The problem
was that in our existing relationships in MIDAS between the objects in
CIDOC CRM do not exist.  Therefore we used 'E13 Attribute Assignment' in
many cases. This solution will be discussed with KHI and BH. What do you
think about it?

3. Our data can be used for reconciliation. The type of work is in
<a5230> and the aat vocabulary is in <a523nr>.

**Comment by mafragias** [comment]
Regarding issue 1: it is updated in the mappings.
