### ISSUE TITLE
Bibliography field duplication

### ISSUE THREAD

**Issue by spykoulouris** [ArtResearch/pharos-mappings#170]
At the Zeri records each value in the Bibliography field appears twice (each time in a different way).

We want the complete version of the citation (the format should be: [author], [title], [date], [pages]), but **not** include the labels of the subfields. Type of bibliography should excluded.

For instance the first Bibliography field in this record will be:
"_Fredericksen B.B./ Zeri F., Census of Pre-Nineteenth-Century Italian Paintings in North American Public Collections, 1972, pp. 107, 646_"
 
https://artresearch.net/resource/?uri=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fpharos%2Fartwork%2F046789776

**Comment by mafragias** [comment]
Fixed in Mappings it will be visible with the next data import.

**Comment by MinadakisNikos** [comment]
@mafragias its done right?
