### ISSUE TITLE
Artists records corrections

### ISSUE THREAD

**Issue by spykoulouris** [ArtResearch/pharos-mappings#173]
There are some things to fix in the Artists records:

1. duplicated labels from the same source
2. IDs from external vocabs without a label (ulan, gnd)
![ids](https://user-images.githubusercontent.com/73180833/114031753-f7292400-987b-11eb-9722-c820cfbf6742.PNG)

3. In the Michelangelo Buonarroti record the Birth Place is missing, the Death Place is wrong (Roman instead of Rome)
4. Delete the underscore symbol from the relations labels imported from Ulan ("patron was" instead of "patron_was")

![buonarroti](https://user-images.githubusercontent.com/73180833/114031883-16c04c80-987c-11eb-9517-ee2a09c94590.PNG)

**Comment by MinadakisNikos** [comment]
@mafragias we can close this right?
