### ISSUE TITLE
Frick repositories

### ISSUE THREAD

**Issue by spykoulouris** [ArtResearch/pharos-mappings#174]
Repositories in the Frick's MARC records are cataloged as 590 fields (with indicator **1**).

If the indicator is 9, the field describes the image source. It seems data from 590 with ind. 9 have been mapped as repositories.
In this example the Guggenheim Museum is the source of the image (because the artwork was on loan at the Guggenheim for an exhibition), and not the repository.
https://artresearch.net/resource/?uri=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Ffrick%2Factor%2F1IEPFBH6

original MARC record: https://arcade.nyarc.org/search~S1?/.b1304425/.b1304425/1%2C1%2C1%2CB/marc~b1304425

**Comment by mafragias** [comment]
this will be solved after the new data import is completed.

**Comment by MinadakisNikos** [comment]
590 9 Image source? Actually according to our discussions with them they said this was the actual image id
