### ISSUE TITLE
Andrea Andreani

### ISSUE THREAD

**Issue by spykoulouris** [ArtResearch/pharos-mappings#175]
Wrong information on the Andrea Andreani artist record: https://artresearch.net/resource/?uri=http%3A%2F%2Fvocab.getty.edu%2Fulan%2F500045330

- from **Ulan** instead of active 19th-20th centuries we have:

Birth date: 1800
Death date: 2090

- from the Marburg there is the field "Institution" with value "Italien"

**Comment by spykoulouris** [comment]
It seems the data are messed because there two different Andrea Andreanis (one male the other female):
http://vocab.getty.edu/page/ulan/500045330
http://vocab.getty.edu/page/ulan/500032629

see also issue: https://github.com/ArtResearch/pharos-mappings/issues/171

**Comment by MinadakisNikos** [comment]
@mafragias is this solved now?

**Comment by mafragias** [comment]
The biographic information about Andrea Andreani are like so from ULAN : http://vocab.getty.edu/ulan/bio/4000171734.

And since the matches are now only using hard rules, this artist has not been matched with any other record.

**Comment by spykoulouris** [comment]
It seems to be fine now.

All the records are linked with this Andreani right? http://vocab.getty.edu/page/ulan/500032629

**Comment by MinadakisNikos** [comment]
No, because it needs to be reconciled manually since there is not enough information for the hard rule
