### ISSUE TITLE
Built works filtering

### ISSUE THREAD

**Issue by spykoulouris** [ArtResearch/pharos-mappings#178]
The built work type does not appear in the facets when searching for palazzo. 
Is it the one with the "pharos" label?

![pharos_concept](https://user-images.githubusercontent.com/73180833/114190127-3e321a80-994b-11eb-8b7e-c4222f0e365e.PNG)

**Comment by MinadakisNikos** [comment]
@mafragias lets check this

**Comment by mafragias** [comment]
There are more options when search for Palazzo, including built works.
https://artresearch.net/resource/?selectedtab=Artworks&keyword=palazzo&uri=Default%3ASearchSimple&semanticSearch=N4IgZiBcDaC6A0IBOBTAzgVwDYBcrAF9EATAQx1LRRzSjkVKwEsBzAOwFsU29JQAVKCAAi5UgDoAsqQCeAIxQhEANXwEiIFklIAHABYBlAMYB7HSgMpSSI3vwhBkEWKmyFSkKr7qCQA

**Comment by spykoulouris** [comment]
Thanks now built works type appears.

What is the "pharos" type I find in the Concepts terms in this search? I see all the 8,700 records include that type.

That actually happens to all kind of searches. For example searching for "ceramic" gives me 17 records in the results, and in the Concepts facet there seem to be 17 records with that type.

**Comment by MinadakisNikos** [comment]
Its fine spyros Pharos type stands for the Pharos URIs that we are creating in order to be the authority of the artworks. We can remove it if it seems odd. I am closing this issue
