### ISSUE TITLE
Duplicate record

### ISSUE THREAD

**Issue by spykoulouris** [ArtResearch/pharos-mappings#179]
Can you check these two records? It seems to be a duplication. 
https://artresearch.net/resource/?uri=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fitatti%2Fwork%2F8000842100

https://artresearch.net/resource/?uri=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fpharos%2Fartwork%2F080524915

original record:  http://id.lib.harvard.edu/images/olvwork628210/catalog

**Comment by mafragias** [comment]
The one is the itatti record and the other is the pharos record.
