### ISSUE TITLE
Frick instutition (photograph provider) with label 1IYHQ66N

### ISSUE THREAD

**Issue by AndreasMichelakis** [ArtResearch/pharos-mappings#180]
Running this query:
`SELECT DISTINCT ?provider WHERE {?subject <https://pharos.artresearch.net/resource/fr/Photo_has_provider_Institution> ?provider.
}LIMIT 10
`
I came across this provider:
https://artresearch.net/resource/?uri=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Ffrick%2Fsource%2F1IYHQ66N

The label should be "Frick" instead of 1IYHQ66N

**Comment by mafragias** [comment]
Fixed in mappings, after data update will be
```
https://pharos.artresearch.net/resource/frick/source/Frick
```
