### ISSUE TITLE
Sales fields missing

### ISSUE THREAD

**Issue by spykoulouris** [ArtResearch/pharos-mappings#187]
It seems some 561 MARC fields are missing from the Frick's records. In the example here it is about a sale of the painting. Not sure why the other 561 appear in the Pharos record the sale one is not.

_Sale, Samuel T. Freeman and Co., Philadelphia, Joesph E. Widener Collection, June 20-24, 1944, lot 425 ($1,000)._

https://artresearch.net/resource/?uri=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fpharos%2Fartwork%2F01951813021

https://arcade.nyarc.org:443/record=b1377497~S1

**Comment by mafragias** [comment]
History of Honership field shows the Sales that are in 561 field.
Example: 
https://artresearch.net/resource/?uri=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fpharos%2Fartwork%2F3c0c4d5015861d7a371dfa63fb2227a56eca7c6d 
![image](https://user-images.githubusercontent.com/23557768/132487315-7f3c710f-e6e1-4f77-a4bb-e6974718a05a.png)


(side note: there is issue with this work's images)
