### ISSUE TITLE
Built works ITatti

### ISSUE THREAD

**Issue by mafragias** [ArtResearch/pharos-mappings#188]
Missing ITatti built works from the new data harvest.

OAI-PMH Harvest Configuration:

base url : http://oai.forum.jstor.org/oai/
metadata Prefix : oai_ssio
sets downloaded : 
-- | -- 
SET | NAME
809 | Berenson Art Collection
810 | Biblioteca Berenson
811 | Biblioteca Berenson, Fototeca

**Comment by MinadakisNikos** [comment]
Fixed
