### ISSUE TITLE
Some institutions are also artists

### ISSUE THREAD

**Issue by mafragias** [ArtResearch/pharos-mappings#194]
Example : https://artresearch.net/resource/?uri=https://pharos.artresearch.net/resource/itatti/actor/9000378350

**Comment by MinadakisNikos** [comment]
this problem can be solved if we take into account the qualifier_lkup="creator" - to be solved as soon as possible but since we noticed it now its not so urgent

**Comment by mafragias** [comment]
if qualifier_lkup="associated names" then the agent was mapped as production participant.
