### ISSUE TITLE
Related Documents

### ISSUE THREAD

**Issue by spykoulouris** [ArtResearch/pharos-mappings#197]
Please include the two fields for related documents to KHI's records:

**aob26** (kind of relation)
**a2606** (document no.)

example of record: https://artresearch.net/resource/?uri=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fpharos%2Fartwork%2Fc29a6b8572ecfa8ad371c6f12fe5a4aa859417ed

**Comment by mafragias** [comment]
So just to make it clear, do we still want to have a2664, a2700 and a2780 as Location? or in the case that we have Zusammenhang ( kind of relation ) to add it in a different field?

```
 <aob26>Zusammenhang
      <a2606>07501119</a2606>  
      <a2664>Assisi</a2664>  
      <a2690>Klosterkirche</a2690>  
      <a2700>San Francesco</a2700>  
      <a2740>Oberkirche</a2740>  
      <a2780>Langhaus</a2780> 
    </aob26>
```

**Comment by spykoulouris** [comment]
I think what they want is a different field ("Related Document") for a2606 field

**Comment by mafragias** [comment]
@spykoulouris I took a look on this issue and the artwork mentioned, and in the original page of the artwork from KHI http://photothek.khi.fi.it/documents/obj/70003602?medium=70003602%2Ffld0005301x_p#1 it seams that this part :

```
Beziehung: Obj-Nr. 70003468, Buch, I-08-040
Vorlage: Obj-Nr. 07505463, Zyklus
Beziehung: Obj-Nr. 70003603, Zeichnung
Beziehung: Obj-Nr. 70003601, Bild
```

looks more like related document.

Are we certain that a2606 is related document? Also if so, how would they like to be presented, could please give me us an example?

**Comment by spykoulouris** [comment]
Yes a2606 is what they call related document (it is a related artwork). I wrote back to the KHI people and asked them if they just need the a2606 subfield (as they initially suggested) or something more.

**Comment by mafragias** [comment]
Thank you, please let us know what they respond.

**Comment by spykoulouris** [comment]
I got feedback from the KHI. 
The field should have label "Related Document" and the value should be the number indicated in subfield a2606. They also ask if that value can be a link to related record mentioned there.

**Comment by mafragias** [comment]
Fixed in mappings, it will be available at the next import.


Example in RS just for this work we are seeing here : https://artresearch.net/resource/?uri=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fpharos%2Fartwork%2Fc29a6b8572ecfa8ad371c6f12fe5a4aa859417ed

**Comment by mafragias** [comment]
To add extra related documents. Example from original data :
```
    <aob26>Zusammenhang
      <a2606>07501119</a2606>  
      <a2664>Assisi</a2664>  
      <a2690>Klosterkirche</a2690>  
      <a2700>San Francesco</a2700>  
      <a2740>Oberkirche</a2740>  
      <a2780>Langhaus</a2780> 
    </aob26>  
    <a5007>Beziehung
      <a5008>70003468</a5008>  
      <a5010>Buch</a5010>  
      <a501p>I-08-040</a501p> 
    </a5007>  
    <a5007>Vorlage
      <a5008>07505463</a5008>  
      <a5010>Zyklus</a5010> 
    </a5007>  
    <a5007>Beziehung
      <a5008>70003603</a5008>  
      <a5010>Zeichnung</a5010> 
    </a5007>  
    <a5007>Beziehung
      <a5008>70003601</a5008>  
      <a5010>Bild</a5010> 
    </a5007> 
```

**Comment by spykoulouris** [comment]
Should we close this ticket? We had a meeting with Almut about it
