### ISSUE TITLE
KHI: Issue with Artworks not found by the KHI Partner Page

### ISSUE THREAD

**Issue by MinadakisNikos** [ArtResearch/pharos-mappings#200]
"madonna mit kind" artwork search does not return results here: 
https://artresearch.net/resource/?uri=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fkhi%2Fsource%2FKHI&semanticSearch=N4IgZiBcDaC6A0IBOBTAzgVwDYBcrAF9EATAQx1LRRzSjkVKwEsBzAOwFsU29JQAVKCAAi5UgDoAsqQCeAIxQhEANXwEiIFklIAHABYBlAMYB7HSgMpSSI3vwhBkEWKmyFSkKr7qCQA

It returns KHI results on the landing page keyword search. Check why this is happening.

**Comment by mafragias** [comment]
It seems that the artworks are there, however it most probably is something with the search itself, and not with the data.
![image](https://user-images.githubusercontent.com/23557768/126122911-56618c28-e4d7-44c0-a472-fdb8e5e330ff.png)

https://artresearch.net/resource/?uri=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fkhi%2Fsource%2FKHI&semanticSearch=N4IgZiBcDaoE4FMrwIZRAYzgW0gUQCYBGAfQAUE4BnAewDsQAaERdMOSAdRrgGsSsCFABcEAExLsa2EgEE4wgJZVhTEGKjRoIAEoJaAVzgYkjUIriLkIACroAkpbUA1a6Jw2AngAckkEAByKNjiATRipiAAbigANgZ%2BIAAWwsLekAD0GVE0GCgARgB0AOYIqZ6F4gYZBrEodBkArAAMzUREjZ0AHCAAvr3MdfkIsegAyvU0AARiilNkimVwNGoRVFiK3kr045MzcwtLK8zCBt6xfqAx8Ze2Dk7MrpCg7thevuhBIWJhEWrXCXQKTSmWyuQKJTKwgqVRqdQaLTaHW6fQGmBoBjoqmed38ABlFO44i43JQ3j5EgSiaNmADEgAWADsqxEIgp1js-kcVkepI87P8X1C4UidKBqXSWQA7jLClKAMyFHjFDIEVpEDIADQAsnixhgkghsCgAMSKLEIUpwVGDerFAwoUroG0gIYjDnoKmUYm8nGvd6UwnemnROKA-wTOjTWbzRbCZYs4Rsj44zkgbkkv1kgOfYLCv60sOJYGSjIyqVyxXK1XqrW6-WG40mlSWOjFF3w%2B2OxKo-oAXT7-eYiCotWxwDRYlZVDKVE0feYcUUxToISxHv8ABFWYVtShPMNMxO0cU4ChvEl9TRfGMhMYkhuQNuk7v94ffcfekA

**Comment by MinadakisNikos** [comment]
Update this searches everywhere with the working keyword search

**Comment by AndreasMichelakis** [comment]
Done for Partners pages.
