### ISSUE TITLE
KHI: KHI photoarchive for Artworks does not work for Contextual Search

### ISSUE THREAD

**Issue by MinadakisNikos** [ArtResearch/pharos-mappings#201]
There are not artworks provided by KHI in contextual Search. Solve this ASAP.

**Comment by mafragias** [comment]
In contextual search, I went and chose Work is documented by KHI and it return the results in the following link : 
https://artresearch.net/resource/?uri=Default%3ASearch&semanticSearch=N4IgziBcoCYPZRAMwMaQO5wE4GsQBoQUoBtULAUynIENEUBXMAFzgFtIBLAOxc%2BYbNOcbgRCVESLJADq2HAH0AFjTAKADljgA3TjApYFASV5CBQkWJikSIAEoUwcBlhRV8oTlk7UQAFUQjbzEANV9mAzY-AE91KkgQADkaNgoYRLh9MW0aABsGeJAlZmZ1MEgAegr1FS0wADoaLGZKMAomlCV67gpmCtbnVwoKnCVOCqcXNwqAaQAJIxAAXyXCXJoAIwpcxHnFwn0wFG91C1EEvbEBdVz40DAGAHNHxzPfAISgn0Iw6BAIrBRWKFZKpdKZdwgHL5QrFUrlKo1JpwBpNFqOdquLo9PoDKbDUbjSZDWYLZarEDrLY7P4fEAAGX4BjyoXCkRicUQjIBLMI0IKuzJBxozBFwPegWCPzZgI5IJSaQyWT5eQFCTh6kqFXQOvq6AAzPVsI8KgAmAAM5oAjBUABoAWXpAGVOhQ2DQAMQsbzcR7ktY0X0MGgvRDklYAXQjFIY3E4AEcCkZrJBzUto4QkKQI4RWgxcsxqBSYCLVL0IJASDmQHlOI9uKluIXaYgACKl%2Br2mjRLas6ArQiPLA0GouuBxJ2YzoShLt0Wd7u96X9lZAA
