### ISSUE TITLE
Alinari has three URIs

### ISSUE THREAD

**Issue by MinadakisNikos** [ArtResearch/pharos-mappings#202]
Alinari search in Photographers collection returns 3 results. One for Wikidata and 2 from PIC. Only one should have the type "pharos" to be searchable since this is the reconciled one (wikidata one)

**Comment by mafragias** [comment]
I removed the type from the reconciled photographers, now it only returns the wikidata instance for Alinary and the rest of the reconciled photographers.
https://artresearch.net/resource/?uri=Default%3ADisplayPharosPhotographers&semanticSearch=N4IgZiBcDaC6A0IBOBTAzgVwDYBcrAF9EATAQx1LRRzSjkVKwEsBzAOwFsU29JQAVKCAAi5UgDoAsqQCeAIxQhEANXwEiIFklIAHABYBlAMYB7HSgMpSSI3vwhBkEWKmyFSkKr7qCQA
