### ISSUE TITLE
Images From KHI (gesperrt)

### ISSUE THREAD

**Issue by mafragias** [ArtResearch/pharos-mappings#209]
Images from KHI have gesperrt, which means there are no rights for sharing these images.

Example:   
```
      <a8450>
         Foto
         <a8496>1964.06.27</a8496>
         <a84fl>197946</a84fl>
         <a8515>Landschaften</a8515>
         <a8460>Alinari</a8460>
         <a8487>Albuminpapier</a8487>
         <a8596>Cimelia Photographica (Standardformat)</a8596>
         <a8497>Altbestand</a8497>
         <a8470>5167</a8470>
         <a8480>25,2 x 18,5 cm (Foto)</a8480>
         <a8482>monochrom</a8482>
         <a8540 edp:checksum="" 
                      edp:lastupdate="2016-06-20T11:16:47Z" 
                      edp:originalfilename="" 
                      edp:originalfilesource=""
                      edp:updateby="EP-User" 
                      edp:virtualfilename="">jouve_KHI-Test4443</a8540>
         <a8541>gesperrt</a8541>
         <a8510>Der Wasserfall von Marmore (La Cascata delle Marmore) in der Nähe von Terni</a8510>
      </a8450>
```
Should we leave the metada as information in the platform ? or just delete the photos completely ?

**Comment by MinadakisNikos** [comment]
we deleted these right?

**Comment by mafragias** [comment]
We deleted the photos, yes

**Comment by mafragias** [comment]
Should we keep the metadata for the gesperrt tagged images or remove the metadata completely?

Example of gesperrt photo metadata in platform:
https://artresearch.net/resource/?uri=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Fkhi%2Fphoto%2Fjouve_KHI-Test4443

![image](https://user-images.githubusercontent.com/23557768/132466396-e083e3a7-3dd1-47a0-bb97-fc10970cd6b5.png)
