### ISSUE TITLE
Missing Date in KHI-record

### ISSUE THREAD

**Issue by mafragias** [ArtResearch/pharos-mappings#212]
In KHI artwork we have Umbau besides Datierung.

Example in Data:
```
  <a5060>Datierung
    <a5064>um 1630</a5064>  
    <a5071 edp:augmented="no:reference">1620</a5071>
    <a5077 edp:augmented="no:reference">1640</a5077>
  </a5060>  
  <a5060>Umbau
    <a5064>1634/1643</a5064>  
    <a5071 edp:augmented="no:reference">1634</a5071>
    <a5077 edp:augmented="no:reference">1643</a5077>
  </a5060>
```

We have only assigned the cases where it is Datierung, Restaurierung, Zerstörung, Umgestaltung. However, we have not mapped the cases where in the field a5060, we have ältere Datierung, Baubeginn, Gründung, Vollendung, Teilabbruch, Umbau, Auftragsvergabe and more.

**Comment by mafragias** [comment]
Hey @spykoulouris could we have a clariffication on this?

**Comment by mafragias** [comment]
Complete List of a5060 elements : 

|a5060|
| --- |
|Datierung (Ostflügel) |
|Einweihung |
|Umwidmung |
|Verlegung|
|Neubau|
|Stiftung|
|Zerteilung|
|Neuweihe|
|Umgestaltung (innen)|
|Teilzerstörung (Diebstahl)|
|Umbau & Erweiterung|
|Datierung (Wagen)|
|Wiedereröffnung|
|Umbau (Fassade)|
|Profanierung & Umbau|
|Neugestaltung|
|Weihe (Kirche)|
|Funddatierung|
|Teilerneuerung|
|Umbau (innen)|
|Grundsteinlegung|
|Abnahme|
|ältere Datierung|
|Umbau & Ausbau|
|Datierung (Nordostflügel)|
|Ersterwähnung|
|Datierung (Original)|
|Baubeginn & Vollendung|
|Teilrekonstruktion|
|Schließung|
|Translozierung|
|Zerstörung|
|Erste Auflage|
|Teilzerstörung (Brand)?|
|Erweiterung|
|Neubau (Moschee)|
|Umnutzung|
|Zerstörung & Neubau|
|Dekoration|
|Datierung (Empore)|
|Wiederherstellung|
|Restaurierung|
|Erneuerung & Teilzerstörung|
|Wiederaufbau|
|Ergänzung|
|Teilzerstörung (Blitzschlag)|
|Eroberung|
|Datierung|
|Ausführung|
|Auflage|
|Datierung (Vorbild)?|
|Erneuerung|
|Verfall|
|Beginn|
|Baubeginn?|
|Eröffnung|
|Versteigerung|
|Teilabbruch & Profanierung|
|Ausgrabung|
|Zerstörung (Brand) & Wiederaufbau|
|Erweiterung (zweite)|
|Überarbeitung|
|Rekonstruktion|
|Datierung (Kirche)|
|Restaurierung (innen)|
|Teilzerstörung|
|Umbau & Umgestaltung|
|Teilzerstörung (Bombentreffer)|
|Restaurierung & Erweiterung|
|Freilegung|
|Baubeginn|
|Übermalung?|
|aufgegeben|
|Sicherung|
|Weihe (Neubau)|
|Entwurf|
|Weihe|
|Aufstellung|
|Vollendung|
|Erneuerung & Erweiterung|
|Datierung (Kopf)|
|Ausbau|
|Aufhebung & Teilzerstörung|
|Erneuerung?|
|Datierung (Skizzenbuch)|
|Zerstörung (Brand)|
|Datierung (Brunnen)|
|Datierung (Vorbild)|
|Umarbeitung|
|Erneuerung & Rekonstruktion|
|Profanierung|
|Überarbeitung (zweite)|
|Umbau?|
|Teilzerstörung (Erdbeben)|
|Rekonstruktion?|
|Umgestaltung (außen)|
|Restaurierung & Rekonstruktion|
|Erweiterung (Presbyterium)|
|Erneuerung (innen)|
|Restaurierung (außen)|
|Überarbeitung?|
|Restaurierung & Ausbau|
|Auftragsvergabe|
|Vollendung (Apsis)|
|Datierung (Kernbau)|
|Umbau|
|Übermalung|
|Neubau (dritter)|
|Neubau (zweiter)|
|Zerstörung (Diebstahl)|
|Datierung (Portal)|
|Datierung (Kreuzgang)|
|Erweiterung & Umbau|
|Aufstockung|
|Vollendung (Fassade)|
|Ergänzung?|
|Datierung (Fassade)|
|Umgestaltung|
|Guss|
|Befestigung|
|Einsturz|
|Planung|
|Teilzerstörung (Hochwasser)|
|Zerstörung (Bombentreffer)|
|Datierung (Vorlage)|
|Neuaufstellung|
|Zerstörung (Erdbeben)|
|Erneuerung (außen)|
|Auslagerung?|
|Teilzerstörung (Brand)|
|Datierung (Kernbau) & Dekoration|
|Teilzerstörung (Vulkanausbruch)|
|Druck|
|Zerstörung (Vulkanausbruch)|
|Aufhebung|
|Zerteilung?|
|Abbruch|
|Restaurierung (Abnahme)|
|Datierung (Turm)|
|Teilübermalung|
|Erweiterung (Fassade)|
|Teileinsturz|
|Weiterführung|
|Purifizierung|
|Teilabbruch|
|Nachguss|
|Restaurierung & Teilzerstörung|
|Ergänzung & Überarbeitung|
|Gründung|
|Umnutzung (Moschee)|

**Comment by spykoulouris** [comment]
I'll check with the KHI and will let you know.

**Comment by spykoulouris** [comment]
Regarding fields aob30 and a5060 (#211) the KHI asks if we can add these terms in a parenthesis after the name of the artist/date.

i.e. 
aob30
Creator: Curradi, Raffaello (Herstellung)
                Salvestrini, Cosmo (Mitarbeit)

a5060
Production date: 1251/1300 (Datierung)
                                  1545/1564 (Neubau)


Otherwise we will need to check with them all of these terms and add them in the modeling.

**Comment by mafragias** [comment]
Example : 
![image](https://user-images.githubusercontent.com/23557768/147247417-ac0e7ed1-78a7-4395-a0d5-b8504b113a05.png)
