### ISSUE TITLE
Artists data from ULAN

### ISSUE THREAD

**Issue by spykoulouris** [ArtResearch/pharos-mappings#214]
Could you please check the mappings of the ULAN data?

In the examples of [Yannis Tsarouchis](https://artresearch.net/resource/?uri=http%3A%2F%2Fvocab.getty.edu%2Fulan%2F500109002) and [Fotis Kontoglou](https://artresearch.net/resource/?uri=http%3A%2F%2Fvocab.getty.edu%2Fulan%2F500080378) they both appear as being tutors of each other. 
The truth is that Tsarouchis was the student and Kontoglou the professor. (see ULAN fields: _apprentice was_ and _apprentice of_).

There might be other examples like this.

Another question is why in the Tsarouchis-Kontoglou records we use the term **tutors** while in other records we use the terms **students** and **teachers**? (i.e. https://artresearch.net/resource/?uri=http%3A%2F%2Fvocab.getty.edu%2Fulan%2F500115228)

**Comment by mafragias** [comment]
Thanks for noticing, i was confused a bit by the ulan relationship, but I am assuming the below meaning is correct :

ulan relationships : 
- [gvp:ulan1105_apprentice_of](http://vocab.getty.edu/resource?uri=http%3A%2F%2Fvocab.getty.edu%2Fontology%23ulan1105_apprentice_of)  : has tutor
- [gvp:ulan1106_apprentice_was](http://vocab.getty.edu/resource?uri=http%3A%2F%2Fvocab.getty.edu%2Fontology%23ulan1106_apprentice_was) : was tutor of

example in ulan :
- [Tsarouhis, Yannis](http://vocab.getty.edu/ulan/500109002)
- [Kontoglou, Fotis](http://vocab.getty.edu/ulan/500080378)

I will update the data and let you know.

**Comment by mafragias** [comment]
Further more we have the term of **tutor** because there is the distinction in ulan : 

- [ulan1102_student_of](http://vocab.getty.edu/resource?uri=http%3A%2F%2Fvocab.getty.edu%2Fontology%23ulan1102_student_of)
- [ulan1101_teacher_of](http://vocab.getty.edu/resource?uri=http%3A%2F%2Fvocab.getty.edu%2Fontology%23ulan1101_teacher_of)

**Comment by spykoulouris** [comment]
Yes, I realized this differentiation comes from ulan. Tutor is for them a more detailed term http://vocab.getty.edu/aat/300025534

**Comment by mafragias** [comment]
I have updated the fields, so the proper connection is shown :

![image](https://user-images.githubusercontent.com/23557768/133761896-9dbf16a1-4ffa-4f78-a92f-7c18b8a1d307.png)

![image](https://user-images.githubusercontent.com/23557768/133761928-ad640188-5e18-47db-a679-661c5dd5e310.png)

**Comment by spykoulouris** [comment]
Great!
Something else I saw is that Tsarouchis has no death date in Pharos, although there is one in ULAN. Could you check why that happens and whether there are dates missing from other artists?

**Comment by mafragias** [comment]
fields are updated : 

![image](https://user-images.githubusercontent.com/23557768/133762653-874bac74-1c5c-4979-82bc-2ac2ec34dad6.png)

![image](https://user-images.githubusercontent.com/23557768/133762688-8b6ffb78-641b-4dbc-9d11-cb0234f133e4.png)

**Comment by mafragias** [comment]
I have now refreshed the ulan death dates and now you are able to notice in [Tsarouchis](https://artresearch.net/resource/?uri=http%3A%2F%2Fvocab.getty.edu%2Fulan%2F500109002) page, his date of death.

![image](https://user-images.githubusercontent.com/23557768/133775056-f60e7a47-b3c1-453b-8d16-e062e5f5745b.png)
