### ISSUE TITLE
Conflicting namespace declarations in Hertziana mappings

### ISSUE THREAD

**Issue by alexdma** [ArtResearch/pharos-mappings#216]
Attempting to run all the Hertziana mappings together on a recent Fototeca dump results in this error:

    The declaration of the namespace with prefix "iiif_json" is not the same in all mapping
    files. (https://foto.biblhertz.it/exist/foto/ != https://img.biblhertz.it/digilib/Scaler/IIIF/fototeca!2048px!im!)
     
Indeed, in [Hertziana/mappings-photos.x3ml](https://github.com/ArtResearch/pharos-mappings/blob/19ae611e3ac4fd758d4ece23782f7c6ad177d15a/Hertziana/mappings-photos.x3ml) there is a namespace declaration for `iiif_json` that does not seem to be used in that particular mapping. Does it have to stay?

Many Thanks

**Comment by mafragias** [comment]
It is used in Generator policies in JSON_Generator: https://github.com/ArtResearch/pharos-mappings/blob/19ae611e3ac4fd758d4ece23782f7c6ad177d15a/Hertziana/generator-policy.xml. So this prefix is required
