### ISSUE TITLE
Frick actor providers

### ISSUE THREAD

**Issue by mafragias** [ArtResearch/pharos-mappings#77]
actor graphs don't have provider

Example : https://artresearch.net/resource/?uri=https%3A%2F%2Fpharos.artresearch.net%2Fresource%2Ffrick%2Factor%2F1IBJTQTO

**Comment by mafragias** [comment]
It is already fixed in mappings.

xm3l mappings provided the below graph for the example above :

<https://pharos.artresearch.net/resource/frick/actor/1IBJTQTO/graph> {
    <https://pharos.artresearch.net/resource/frick/actor/1IBJTQTO>
            a       <http://www.cidoc-crm.org/cidoc-crm/E21_Person> , <http://www.cidoc-crm.org/cidoc-crm/E41_Appellation> ;
            <http://www.w3.org/2000/01/rdf-schema#label>
                    "Newman, Barnett" ;
            <http://www.cidoc-crm.org/cidoc-crm/P1_is_identified_by>
                    <https://pharos.artresearch.net/resource/frick/actor/1IBJTQTO> ;
            <http://www.cidoc-crm.org/cidoc-crm/P2_has_type>
                    <http://vocab.getty.edu/aat/300417193> ;
            <http://www.cidoc-crm.org/cidoc-crm/P67i_is_referred_to_by>
                    <https://pharos.artresearch.net/resource/frick/actor/1IBJTQTO/graph> ;
            <http://www.cidoc-crm.org/cidoc-crm/P98i_was_born_by>
                    <https://pharos.artresearch.net/resource/frick/actor/Newman%2C%20Barnett/birth> ;
            <https://pharos.artresearch.net/custom/has_provider>
                    <https://pharos.artresearch.net/resource/frick/source/Frick> .
    
    <https://pharos.artresearch.net/resource/frick/source/Frick>
            a       <https://pharos.artresearch.net/custom/Provider> ;
            <http://www.w3.org/2000/01/rdf-schema#label>
                    "Frick" .
    
    <https://pharos.artresearch.net/resource/frick/actor/1IBJTQTO/graph>
            a       <https://pharos.artresearch.net/custom/Namedgraph> ;
            <https://pharos.artresearch.net/custom/has_provider>
                    <https://pharos.artresearch.net/resource/frick/source/Frick> .
    
    <http://vocab.getty.edu/aat/300417193>
            a       <http://www.cidoc-crm.org/cidoc-crm/E55_Type> ;
            <http://www.w3.org/2000/01/rdf-schema#label>
                    "titles (general, names)" .
    
    <https://pharos.artresearch.net/resource/frick/actor/Newman%2C%20Barnett/birth>
            a       <http://www.cidoc-crm.org/cidoc-crm/E67_Birth> ;
            <http://www.cidoc-crm.org/cidoc-crm/P4_has_time-span>
                    <https://pharos.artresearch.net/resource/frick/actor/Newman%2C%20Barnett/birth/timespan> .
    
    <https://pharos.artresearch.net/resource/frick/actor/Newman%2C%20Barnett/birth/timespan>
            a       <http://www.cidoc-crm.org/cidoc-crm/E52_Time-Span> ;
            <http://www.cidoc-crm.org/cidoc-crm/P82_at_some_time_within>
                    "1905-1970" .
}

Note: After the next run of ETL with the updated mappings, the graphs in pharos will be updated.

**Comment by MinadakisNikos** [comment]
great. close it

**Comment by mafragias** [comment]
Issue Validated
