### ISSUE TITLE
FotoIndex Place URI

### ISSUE THREAD

**Issue by mafragias** [ArtResearch/pharos-mappings#78]
fix fotoindex place uri, because it maps place with the same wrongly.

**Comment by mafragias** [comment]
changed the mappings for places of institutions and creating a new generator policy.

Generator Policy : 
```
<generator name="PlaceURIwithType" prefix="prefix" shorten="yes">
	<pattern>{type}/{resourceId}/{id}</pattern>
</generator>
```

Example result : https://pharos.artresearch.net/resource/itatti/place/N00000002/1H7O64GS

**Comment by MinadakisNikos** [comment]
great close it

**Comment by mafragias** [comment]
Issue validated
