### ISSUE TITLE
Frick mapping for a photo <link> xpath

### ISSUE THREAD

**Issue by mafragias** [ArtResearch/pharos-mappings#80]
Frick mappings : marc:datafield[@tag="590" and @ind1="9"]/marc:subfield[@code="m"], In this case of mapping it should have been just  marc:subfield[@code="m"] like the previous mapping of photo.

marc:datafield[@tag="590" and @ind1="9"]/marc:subfield[@code="k"] in Digital image mapping is just marc:subfield[@code="j"]?

**Comment by mafragias** [comment]
marc:datafield[@tag="590" and @ind1="9"]/marc:subfield[@code="m"] to marc:subfield[@code="m"]
marc:datafield[@tag="590" and @ind1="9"]/marc:subfield[@code="k"] to marc:subfield[@code="j"]

Reason: Domain is already marc:datafield[@tag="590" and @ind1="9"] and in the second case is "j" because the source relation is also marc:subfield[@code="j"]

**Comment by MinadakisNikos** [comment]
ok close it

**Comment by mafragias** [comment]
Issue Validated
