### ISSUE TITLE
MIDAS mappings a5117

### ISSUE THREAD

**Issue by mafragias** [ArtResearch/pharos-mappings#81]
a5117 field : mapped duplicate and there are no data transformed. (although it has different types Address and Street)

**Comment by mafragias** [comment]
changing a5117 mapping to a5108/a5116. And keeping only Street type.

**Comment by mafragias** [comment]
changing a5117 mapping to a5108/a5117. And giving Street Number type.

**Comment by MinadakisNikos** [comment]
cool, close it

**Comment by mafragias** [comment]
Issue Validated
