### ISSUE TITLE
slash instead of %2F

### ISSUE THREAD

**Issue by mafragias** [ArtResearch/pharos-mappings#85]
Example vocabulary/technique becames vocabulary%2Ftechnique.

Solution : Create new policy?

**Comment by mafragias** [comment]
Changed in 
Frick 👍
Itatti FotoIndex 👎 didn't have any instances of vocabulary
Itatti SharedShelf 👍 
Zeri 👍 
Marburg 👍 
KHI 👍 
Hertziana 👍 
POLICY : 
<generator name="URIwithVocabType" prefix="vocab" shorten="yes">
	<pattern>{type}/{id}</pattern>
</generator>
Prefix example: 
<namespace prefix="vocab" uri="https://pharos.artresearch.net/resource/frick/vocabulary/"/>
Mapping example :
<instance_generator name="URIwithVocabType">
  <arg name="type" type="constant">technique</arg>
  <arg name="id" type="xpath">text()</arg>
</instance_generator>
fc mapping example : 
<type>fc:technique</type>
<instance_generator name="URIwithVocabType">
  <arg name="type" type="constant">technique</arg>
  <arg name="id" type="xpath">text()</arg>
</instance_generator>
Result examples:
https://pharos.artresearch.net/resource/frick/vocabulary/technique/1HROTGOT
https://pharos.artresearch.net/resource/itatti/vocabulary/technique/1JEFYNYT
https://pharos.artresearch.net/resource/midas/vocabulary/material/UBGVNSY4
https://pharos.artresearch.net/resource/midas/vocabulary/technique/SKNB8KZJ

**Comment by MinadakisNikos** [comment]
great close it

**Comment by mafragias** [comment]
Added extra generator policy for those cases where they originally had URIwithTypeAndId
```
<generator name="URIwithVocabTypeAndId" prefix="vocab" shorten="yes">
	<pattern>{type}/{id}</pattern>
</generator>
```
Closing as the issue is validated
