### ISSUE TITLE
Instance Matching Graphs Refinement

### ISSUE THREAD

**Issue by mafragias** [ArtResearch/pharos-mappings#91]
Refine name of Graphs for instance matchings and also create separate graphs for each provider and category (works/artists/places/photographers/institutions/types)

example : <https://pharos.artresearch.net/resource/pharos/matched/artists/graph> instead of <https://matched>

Artists : 
https://pharos.artresearch.net/resource/pharos/matched/artists/graph
https://pharos.artresearch.net/resource/pharos/hashed/artists/graph

Artworks : 
https://pharos.artresearch.net/resource/pharos/matched/artworks/graph
https://pharos.artresearch.net/resource/pharos/hashed/artworks/graph

Institutions : 
https://pharos.artresearch.net/resource/pharos/matched/institutions/graph
https://pharos.artresearch.net/resource/pharos/hashed/institutions/graph

Photographers : 
https://pharos.artresearch.net/resource/pharos/matched/photographers/graph
https://pharos.artresearch.net/resource/pharos/hashed/photographers/graph

Places : 
https://pharos.artresearch.net/resource/pharos/matched/places/graph
https://pharos.artresearch.net/resource/pharos/hashed/places/graph

Vocabularies : 
https://pharos.artresearch.net/resource/pharos/matched/vocabularies/graph
https://pharos.artresearch.net/resource/pharos/hashed/vocabularies/graph

**Comment by MinadakisNikos** [comment]
@mafragias can we update this list?

**Comment by mafragias** [comment]
This list is indeed deprecated, since we no logner have hashes for any category other than artworks. 

Artists :
https://pharos.artresearch.net/resource/pharos/matched/artists/graph

Artworks :
https://pharos.artresearch.net/resource/pharos/matched/artworks/graph
https://pharos.artresearch.net/resource/pharos/hashed/artworks/graph

Institutions :
https://pharos.artresearch.net/resource/pharos/matched/institutions/graph

Photographers :
https://pharos.artresearch.net/resource/pharos/matched/photographers/graph

Places :
https://pharos.artresearch.net/resource/pharos/matched/places/graph

Vocabularies :
for vocabularies instance matching process is coming from the partners' data. So each case of vocabularies matching with aat is in their respective graph.
